name: app
description: A new Flutter application to solve ios issue.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2
  simple_animations: ^1.3.3
  curved_navigation_bar: ^0.3.2
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  image_cropper: ^1.2.2
  image_picker: ^0.6.6+1
  time_ago_provider: ^1.0.3
  intl: ^0.16.1
  folding_cell: ^0.1.2
  charts_flutter: ^0.9.0
  cached_network_image: ^2.1.0+1
  share: ^0.6.4
  flip_card: ^0.4.4
  progress_dialog: ^1.2.3
  youtube_player_flutter: ^7.0.0+7
  flutter_launcher_icons: ^0.7.5


  image: ^2.0.7
  animator: 0.1.4
  timeago: 2.0.17
  geolocator: 5.0.1
  uuid: ^2.0.0
  path_provider: ^1.6.7
  firebase_messaging: ^4.0.0+1
  flutter_svg:
  url_launcher: ^5.4.11

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: ArchivoNarrow
      fonts:
        - asset: assets/fonts/ArchivoNarrow-Bold.ttf
        - asset: assets/fonts/ArchivoNarrow-Regular.ttf


  assets:
    - assets/images/



